#!/bin/bash
# Auto-generated rename script for Gemini CLI documentation
# Generated: 2026-01-13T19:17:29.604098

cd "/home/diogo/dev/library-docs/docs_geminiclicom"

mv "index.md" "001-index.md"
mv "docs.md" "002-docs.md"
mv "docs-get-started.md" "003-docs-get-started.md"
mv "docs-get-started-installation.md" "004-docs-get-started-installation.md"
mv "docs-get-started-authentication.md" "005-docs-get-started-authentication.md"
mv "docs-get-started-configuration.md" "006-docs-get-started-configuration.md"
mv "docs-get-started-configuration-v1.md" "007-docs-get-started-configuration-v1.md"
mv "docs-get-started-examples.md" "008-docs-get-started-examples.md"
mv "docs-get-started-gemini-3.md" "009-docs-get-started-gemini-3.md"
mv "docs-cli.md" "010-docs-cli.md"
mv "docs-cli-commands.md" "011-docs-cli-commands.md"
mv "docs-cli-settings.md" "012-docs-cli-settings.md"
mv "docs-cli-model.md" "013-docs-cli-model.md"
mv "docs-cli-themes.md" "014-docs-cli-themes.md"
mv "docs-cli-keyboard-shortcuts.md" "015-docs-cli-keyboard-shortcuts.md"
mv "docs-cli-session-management.md" "016-docs-cli-session-management.md"
mv "docs-cli-checkpointing.md" "017-docs-cli-checkpointing.md"
mv "docs-cli-sandbox.md" "018-docs-cli-sandbox.md"
mv "docs-cli-headless.md" "019-docs-cli-headless.md"
mv "docs-cli-custom-commands.md" "020-docs-cli-custom-commands.md"
mv "docs-cli-skills.md" "021-docs-cli-skills.md"
mv "docs-cli-enterprise.md" "022-docs-cli-enterprise.md"
mv "docs-cli-trusted-folders.md" "023-docs-cli-trusted-folders.md"
mv "docs-cli-system-prompt.md" "024-docs-cli-system-prompt.md"
mv "docs-cli-token-caching.md" "025-docs-cli-token-caching.md"
mv "docs-cli-telemetry.md" "026-docs-cli-telemetry.md"
mv "docs-cli-tutorials.md" "027-docs-cli-tutorials.md"
mv "docs-cli-uninstall.md" "028-docs-cli-uninstall.md"
mv "docs-cli-gemini-md.md" "029-docs-cli-gemini-md.md"
mv "docs-cli-gemini-ignore.md" "030-docs-cli-gemini-ignore.md"
mv "docs-cli-authentication.md" "031-docs-cli-authentication.md"
mv "docs-cli-tutorials-skills-getting-started.md" "032-docs-cli-tutorials-skills-getting-started.md"
mv "docs-architecture.md" "033-docs-architecture.md"
mv "docs-core.md" "034-docs-core.md"
mv "docs-core-policy-engine.md" "035-docs-core-policy-engine.md"
mv "docs-core-tools-api.md" "036-docs-core-tools-api.md"
mv "docs-core-memport.md" "037-docs-core-memport.md"
mv "docs-tools.md" "038-docs-tools.md"
mv "docs-tools-file-system.md" "039-docs-tools-file-system.md"
mv "docs-tools-shell.md" "040-docs-tools-shell.md"
mv "docs-tools-web-search.md" "041-docs-tools-web-search.md"
mv "docs-tools-web-fetch.md" "042-docs-tools-web-fetch.md"
mv "docs-tools-memory.md" "043-docs-tools-memory.md"
mv "docs-tools-todos.md" "044-docs-tools-todos.md"
mv "docs-tools-mcp-server.md" "045-docs-tools-mcp-server.md"
mv "docs-extensions.md" "046-docs-extensions.md"
mv "docs-extensions-getting-started-extensions.md" "047-docs-extensions-getting-started-extensions.md"
mv "docs-extensions-extension-releasing.md" "048-docs-extensions-extension-releasing.md"
mv "docs-hooks.md" "049-docs-hooks.md"
mv "docs-hooks-writing-hooks.md" "050-docs-hooks-writing-hooks.md"
mv "docs-hooks-best-practices.md" "051-docs-hooks-best-practices.md"
mv "docs-hooks-reference.md" "052-docs-hooks-reference.md"
mv "docs-ide-integration.md" "053-docs-ide-integration.md"
mv "docs-ide-integration-ide-companion-spec.md" "054-docs-ide-integration-ide-companion-spec.md"
mv "docs-npm.md" "055-docs-npm.md"
mv "docs-integration-tests.md" "056-docs-integration-tests.md"
mv "docs-issue-and-pr-automation.md" "057-docs-issue-and-pr-automation.md"
mv "docs-contributing.md" "058-docs-contributing.md"
mv "docs-releases.md" "059-docs-releases.md"
mv "docs-changelogs.md" "060-docs-changelogs.md"
mv "docs-changelogs-releases.md" "061-docs-changelogs-releases.md"
mv "docs-changelogs-latest.md" "062-docs-changelogs-latest.md"
mv "docs-changelogs-preview.md" "063-docs-changelogs-preview.md"
mv "docs-faq.md" "064-docs-faq.md"
mv "docs-troubleshooting.md" "065-docs-troubleshooting.md"
mv "docs-quota-and-pricing.md" "066-docs-quota-and-pricing.md"
mv "docs-tos-privacy.md" "067-docs-tos-privacy.md"

echo "Rename complete: 67 files renamed"
