#!/bin/bash
# Documentation rename script for komorebi

# Category 1: Introduction & Overview (001-002)
mv "docs-index.md" "001-docs-index.md"
mv "docs-installation.md" "002-docs-installation.md"

# Category 2: Usage Guides (003-007)
mv "docs-usage-stacking-windows.md" "003-docs-usage-stacking-windows.md"
mv "docs-usage-moving-windows.md" "004-docs-usage-moving-windows.md"
mv "docs-usage-moving-windows-across-workspaces.md" "005-docs-usage-moving-windows-across-workspaces.md"
mv "docs-usage-focusing-windows.md" "006-docs-usage-focusing-windows.md"
mv "docs-usage-focusing-workspaces.md" "007-docs-usage-focusing-workspaces.md"

# Category 3: Configuration & Design (008-009)
mv "docs-design.md" "008-docs-design.md"
mv "docs-example-configurations.md" "009-docs-example-configurations.md"

# Category 4: Common Workflows (010-025)
mv "docs-common-workflows-autohotkey.md" "010-docs-common-workflows-autohotkey.md"
mv "docs-common-workflows-animations.md" "011-docs-common-workflows-animations.md"
mv "docs-common-workflows-autostart.md" "012-docs-common-workflows-autostart.md"
mv "docs-common-workflows-borders.md" "013-docs-common-workflows-borders.md"
mv "docs-common-workflows-dynamic-layout-switching.md" "014-docs-common-workflows-dynamic-layout-switching.md"
mv "docs-common-workflows-floating-applications.md" "015-docs-common-workflows-floating-applications.md"
mv "docs-common-workflows-force-manage-windows.md" "016-docs-common-workflows-force-manage-windows.md"
mv "docs-common-workflows-ignore-windows.md" "017-docs-common-workflows-ignore-windows.md"
mv "docs-common-workflows-komorebi-config-home.md" "018-docs-common-workflows-komorebi-config-home.md"
mv "docs-common-workflows-layout-ratios.md" "019-docs-common-workflows-layout-ratios.md"
mv "docs-common-workflows-mouse-follows-focus.md" "020-docs-common-workflows-mouse-follows-focus.md"
mv "docs-common-workflows-multi-monitor-setup.md" "021-docs-common-workflows-multi-monitor-setup.md"
mv "docs-common-workflows-multiple-bar-instances.md" "022-docs-common-workflows-multiple-bar-instances.md"
mv "docs-common-workflows-remove-gaps.md" "023-docs-common-workflows-remove-gaps.md"
mv "docs-common-workflows-stackbar.md" "024-docs-common-workflows-stackbar.md"
mv "docs-common-workflows-tray-and-multi-window-applications.md" "025-docs-common-workflows-tray-and-multi-window-applications.md"

# Category 5: Troubleshooting (026)
mv "docs-troubleshooting.md" "026-docs-troubleshooting.md"

# Category 6: CLI Reference - Start/Stop/State (027-033)
mv "docs-cli-start.md" "027-docs-cli-start.md"
mv "docs-cli-stop.md" "028-docs-cli-stop.md"
mv "docs-cli-state.md" "029-docs-cli-state.md"
mv "docs-cli-reload-configuration.md" "030-docs-cli-reload-configuration.md"
mv "docs-cli-watch-configuration.md" "031-docs-cli-watch-configuration.md"
mv "docs-cli-replace-configuration.md" "032-docs-cli-replace-configuration.md"
mv "docs-cli-configuration.md" "033-docs-cli-configuration.md"

# CLI Reference - Quick Save/Load (034-037)
mv "docs-cli-quick-save-resize.md" "034-docs-cli-quick-save-resize.md"
mv "docs-cli-quick-load-resize.md" "035-docs-cli-quick-load-resize.md"
mv "docs-cli-save-resize.md" "036-docs-cli-save-resize.md"
mv "docs-cli-load-resize.md" "037-docs-cli-load-resize.md"

# CLI Reference - Focus Commands (038-052)
mv "docs-cli-focus.md" "038-docs-cli-focus.md"
mv "docs-cli-focus-monitor.md" "039-docs-cli-focus-monitor.md"
mv "docs-cli-focus-monitor-at-cursor.md" "040-docs-cli-focus-monitor-at-cursor.md"
mv "docs-cli-focus-monitor-workspace.md" "041-docs-cli-focus-monitor-workspace.md"
mv "docs-cli-focus-workspace.md" "042-docs-cli-focus-workspace.md"
mv "docs-cli-focus-named-workspace.md" "043-docs-cli-focus-named-workspace.md"
mv "docs-cli-focus-last-workspace.md" "044-docs-cli-focus-last-workspace.md"
mv "docs-cli-focus-workspaces.md" "045-docs-cli-focus-workspaces.md"
mv "docs-cli-focus-stack-window.md" "046-docs-cli-focus-stack-window.md"
mv "docs-cli-eager-focus.md" "047-docs-cli-eager-focus.md"
mv "docs-cli-force-focus.md" "048-docs-cli-force-focus.md"
mv "docs-cli-cycle-focus.md" "049-docs-cli-cycle-focus.md"

# CLI Reference - Move Commands (050-072)
mv "docs-cli-move.md" "050-docs-cli-move.md"
mv "docs-cli-move-to-workspace.md" "051-docs-cli-move-to-workspace.md"
mv "docs-cli-move-to-named-workspace.md" "052-docs-cli-move-to-named-workspace.md"
mv "docs-cli-move-to-monitor.md" "053-docs-cli-move-to-monitor.md"
mv "docs-cli-move-to-monitor-workspace.md" "054-docs-cli-move-to-monitor-workspace.md"
mv "docs-cli-move-to-last-workspace.md" "055-docs-cli-move-to-last-workspace.md"
mv "docs-cli-move-workspace-to-monitor.md" "056-docs-cli-move-workspace-to-monitor.md"
mv "docs-cli-cycle-move.md" "057-docs-cli-cycle-move.md"
mv "docs-cli-cycle-move-to-workspace.md" "058-docs-cli-cycle-move-to-workspace.md"
mv "docs-cli-cycle-move-to-monitor.md" "059-docs-cli-cycle-move-to-monitor.md"
mv "docs-cli-cycle-move-workspace-to-monitor.md" "060-docs-cli-cycle-move-workspace-to-monitor.md"
mv "docs-cli-send-to-workspace.md" "061-docs-cli-send-to-workspace.md"
mv "docs-cli-send-to-named-workspace.md" "062-docs-cli-send-to-named-workspace.md"
mv "docs-cli-send-to-monitor.md" "063-docs-cli-send-to-monitor.md"
mv "docs-cli-send-to-monitor-workspace.md" "064-docs-cli-send-to-monitor-workspace.md"
mv "docs-cli-send-to-last-workspace.md" "065-docs-cli-send-to-last-workspace.md"

# CLI Reference - Workspace Commands (066-097)
mv "docs-cli-new-workspace.md" "066-docs-cli-new-workspace.md"
mv "docs-cli-close-workspace.md" "067-docs-cli-close-workspace.md"
mv "docs-cli-workspace-name.md" "068-docs-cli-workspace-name.md"
mv "docs-cli-cycle-workspace.md" "069-docs-cli-cycle-workspace.md"
mv "docs-cli-cycle-empty-workspace.md" "070-docs-cli-cycle-empty-workspace.md"
mv "docs-cli-swap-workspaces-with-monitor.md" "071-docs-cli-swap-workspaces-with-monitor.md"
mv "docs-cli-workspace-padding.md" "072-docs-cli-workspace-padding.md"
mv "docs-cli-adjust-workspace-padding.md" "073-docs-cli-adjust-workspace-padding.md"
mv "docs-cli-focused-workspace-padding.md" "074-docs-cli-focused-workspace-padding.md"
mv "docs-cli-workspace-layout.md" "075-docs-cli-workspace-layout.md"
mv "docs-cli-change-layout.md" "076-docs-cli-change-layout.md"
mv "docs-cli-cycle-layout.md" "077-docs-cli-cycle-layout.md"
mv "docs-cli-flip-layout.md" "078-docs-cli-flip-layout.md"
mv "docs-cli-workspace-tiling.md" "079-docs-cli-workspace-tiling.md"
mv "docs-cli-named-workspace-tiling.md" "080-docs-cli-named-workspace-tiling.md"
mv "docs-cli-workspace-layout-rule.md" "081-docs-cli-workspace-layout-rule.md"
mv "docs-cli-named-workspace-layout-rule.md" "082-docs-cli-named-workspace-layout-rule.md"
mv "docs-cli-named-workspace-layout.md" "083-docs-cli-named-workspace-layout.md"
mv "docs-cli-ensure-workspaces.md" "084-docs-cli-ensure-workspaces.md"
mv "docs-cli-ensure-named-workspaces.md" "085-docs-cli-ensure-named-workspaces.md"

# CLI Reference - Container Commands (086-107)
mv "docs-cli-container-padding.md" "086-docs-cli-container-padding.md"
mv "docs-cli-adjust-container-padding.md" "087-docs-cli-adjust-container-padding.md"
mv "docs-cli-focused-workspace-container-padding.md" "088-docs-cli-focused-workspace-container-padding.md"
mv "docs-cli-named-workspace-container-padding.md" "089-docs-cli-named-workspace-container-padding.md"
mv "docs-cli-stack.md" "090-docs-cli-stack.md"
mv "docs-cli-unstack.md" "091-docs-cli-unstack.md"
mv "docs-cli-stack-all.md" "092-docs-cli-stack-all.md"
mv "docs-cli-unstack-all.md" "093-docs-cli-unstack-all.md"
mv "docs-cli-cycle-stack.md" "094-docs-cli-cycle-stack.md"
mv "docs-cli-cycle-stack-index.md" "095-docs-cli-cycle-stack-index.md"
mv "docs-cli-promote.md" "096-docs-cli-promote.md"
mv "docs-cli-promote-window.md" "097-docs-cli-promote-window.md"
mv "docs-cli-promote-focus.md" "098-docs-cli-promote-focus.md"
mv "docs-cli-promote-swap.md" "099-docs-cli-promote-swap.md"
mv "docs-cli-cancel-preselect.md" "100-docs-cli-cancel-preselect.md"
mv "docs-cli-preselect-direction.md" "101-docs-cli-preselect-direction.md"
mv "docs-cli-scrolling-layout-columns.md" "102-docs-cli-scrolling-layout-columns.md"

# CLI Reference - Window Commands (103-127)
mv "docs-cli-close.md" "103-docs-cli-close.md"
mv "docs-cli-minimize.md" "104-docs-cli-minimize.md"
mv "docs-cli-restore-windows.md" "105-docs-cli-restore-windows.md"
mv "docs-cli-retile.md" "106-docs-cli-retile.md"
mv "docs-cli-monocle.md" "107-docs-cli-monocle.md"
mv "docs-cli-maximize.md" "108-docs-cli-maximize.md"
mv "docs-cli-resize-axis.md" "109-docs-cli-resize-axis.md"
mv "docs-cli-resize-delta.md" "110-docs-cli-resize-delta.md"
mv "docs-cli-resize-edge.md" "111-docs-cli-resize-edge.md"
mv "docs-cli-toggle-float.md" "112-docs-cli-toggle-float.md"
mv "docs-cli-toggle-float-override.md" "113-docs-cli-toggle-float-override.md"
mv "docs-cli-toggle-workspace-float-override.md" "114-docs-cli-toggle-workspace-float-override.md"
mv "docs-cli-toggle-monocle.md" "115-docs-cli-toggle-monocle.md"
mv "docs-cli-toggle-maximize.md" "116-docs-cli-toggle-maximize.md"

# CLI Reference - Monitor Commands (117-135)
mv "docs-cli-cycle-monitor.md" "117-docs-cli-cycle-monitor.md"
mv "docs-cli-monitor-information.md" "118-docs-cli-monitor-information.md"
mv "docs-cli-monitor-work-area-offset.md" "119-docs-cli-monitor-work-area-offset.md"
mv "docs-cli-display-index-preference.md" "120-docs-cli-display-index-preference.md"
mv "docs-cli-monitor-index-preference.md" "121-docs-cli-monitor-index-preference.md"

# CLI Reference - Toggles (122-158)
mv "docs-cli-toggle-tiling.md" "122-docs-cli-toggle-tiling.md"
mv "docs-cli-toggle-pause.md" "123-docs-cli-toggle-pause.md"
mv "docs-cli-toggle-lock.md" "124-docs-cli-toggle-lock.md"
mv "docs-cli-toggle-shortcuts.md" "125-docs-cli-toggle-shortcuts.md"
mv "docs-cli-toggle-title-bars.md" "126-docs-cli-toggle-title-bars.md"
mv "docs-cli-toggle-transparency.md" "127-docs-cli-toggle-transparency.md"
mv "docs-cli-toggle-mouse-follows-focus.md" "128-docs-cli-toggle-mouse-follows-focus.md"
mv "docs-cli-mouse-follows-focus.md" "129-docs-cli-mouse-follows-focus.md"
mv "docs-cli-toggle-workspace-layer.md" "130-docs-cli-toggle-workspace-layer.md"
mv "docs-cli-toggle-cross-monitor-move-behaviour.md" "131-docs-cli-toggle-cross-monitor-move-behaviour.md"
mv "docs-cli-cross-monitor-move-behaviour.md" "132-docs-cli-cross-monitor-move-behaviour.md"
mv "docs-cli-toggle-window-based-work-area-offset.md" "133-docs-cli-toggle-window-based-work-area-offset.md"
mv "docs-cli-global-work-area-offset.md" "134-docs-cli-global-work-area-offset.md"
mv "docs-cli-workspace-work-area-offset.md" "135-docs-cli-workspace-work-area-offset.md"
mv "docs-cli-toggle-window-container-behaviour.md" "136-docs-cli-toggle-window-container-behaviour.md"
mv "docs-cli-toggle-workspace-window-container-behaviour.md" "137-docs-cli-toggle-workspace-window-container-behaviour.md"
mv "docs-cli-unmanaged-window-operation-behaviour.md" "138-docs-cli-unmanaged-window-operation-behaviour.md"

# CLI Reference - Window Rules (139-158)
mv "docs-cli-manage.md" "139-docs-cli-manage.md"
mv "docs-cli-unmanage.md" "140-docs-cli-unmanage.md"
mv "docs-cli-manage-rule.md" "141-docs-cli-manage-rule.md"
mv "docs-cli-ignore-rule.md" "142-docs-cli-ignore-rule.md"
mv "docs-cli-workspace-rule.md" "143-docs-cli-workspace-rule.md"
mv "docs-cli-named-workspace-rule.md" "144-docs-cli-named-workspace-rule.md"
mv "docs-cli-initial-workspace-rule.md" "145-docs-cli-initial-workspace-rule.md"
mv "docs-cli-initial-named-workspace-rule.md" "146-docs-cli-initial-named-workspace-rule.md"
mv "docs-cli-session-float-rules.md" "147-docs-cli-session-float-rules.md"
mv "docs-cli-session-float-rule.md" "148-docs-cli-session-float-rule.md"
mv "docs-cli-clear-workspace-rules.md" "149-docs-cli-clear-workspace-rules.md"
mv "docs-cli-clear-named-workspace-rules.md" "150-docs-cli-clear-named-workspace-rules.md"
mv "docs-cli-clear-all-workspace-rules.md" "151-docs-cli-clear-all-workspace-rules.md"
mv "docs-cli-clear-session-float-rules.md" "152-docs-cli-clear-session-float-rules.md"
mv "docs-cli-clear-workspace-layout-rules.md" "153-docs-cli-clear-workspace-layout-rules.md"
mv "docs-cli-clear-named-workspace-layout-rules.md" "154-docs-cli-clear-named-workspace-layout-rules.md"
mv "docs-cli-enforce-workspace-rules.md" "155-docs-cli-enforce-workspace-rules.md"

# CLI Reference - Animation & Border (156-175)
mv "docs-cli-animation.md" "156-docs-cli-animation.md"
mv "docs-cli-animation-duration.md" "157-docs-cli-animation-duration.md"
mv "docs-cli-animation-fps.md" "158-docs-cli-animation-fps.md"
mv "docs-cli-animation-style.md" "159-docs-cli-animation-style.md"
mv "docs-cli-transparency.md" "160-docs-cli-transparency.md"
mv "docs-cli-transparency-alpha.md" "161-docs-cli-transparency-alpha.md"
mv "docs-cli-border.md" "162-docs-cli-border.md"
mv "docs-cli-border-width.md" "163-docs-cli-border-width.md"
mv "docs-cli-border-colour.md" "164-docs-cli-border-colour.md"
mv "docs-cli-border-style.md" "165-docs-cli-border-style.md"
mv "docs-cli-border-offset.md" "166-docs-cli-border-offset.md"
mv "docs-cli-border-implementation.md" "167-docs-cli-border-implementation.md"
mv "docs-cli-invisible-borders.md" "168-docs-cli-invisible-borders.md"
mv "docs-cli-remove-title-bar.md" "169-docs-cli-remove-title-bar.md"

# CLI Reference - Application Detection (170-180)
mv "docs-cli-identify-layered-application.md" "170-docs-cli-identify-layered-application.md"
mv "docs-cli-identify-tray-application.md" "171-docs-cli-identify-tray-application.md"
mv "docs-cli-identify-object-name-change-application.md" "172-docs-cli-identify-object-name-change-application.md"
mv "docs-cli-window-hiding-behaviour.md" "173-docs-cli-window-hiding-behaviour.md"

# CLI Reference - Configuration Tools (174-189)
mv "docs-cli-complete-configuration.md" "174-docs-cli-complete-configuration.md"
mv "docs-cli-generate-static-config.md" "175-docs-cli-generate-static-config.md"
mv "docs-cli-static-config-schema.md" "176-docs-cli-static-config-schema.md"
mv "docs-cli-application-specific-configuration-schema.md" "177-docs-cli-application-specific-configuration-schema.md"
mv "docs-cli-convert-app-specific-configuration.md" "178-docs-cli-convert-app-specific-configuration.md"
mv "docs-cli-fetch-app-specific-configuration.md" "179-docs-cli-fetch-app-specific-configuration.md"
mv "docs-cli-ahk-app-specific-configuration.md" "180-docs-cli-ahk-app-specific-configuration.md"
mv "docs-cli-pwsh-app-specific-configuration.md" "181-docs-cli-pwsh-app-specific-configuration.md"

# CLI Reference - Socket/Pipe & Misc (182-199)
mv "docs-cli-subscribe-socket.md" "182-docs-cli-subscribe-socket.md"
mv "docs-cli-unsubscribe-socket.md" "183-docs-cli-unsubscribe-socket.md"
mv "docs-cli-subscribe-pipe.md" "184-docs-cli-subscribe-pipe.md"
mv "docs-cli-unsubscribe-pipe.md" "185-docs-cli-unsubscribe-pipe.md"
mv "docs-cli-socket-schema.md" "186-docs-cli-socket-schema.md"
mv "docs-cli-notification-schema.md" "187-docs-cli-notification-schema.md"

# CLI Reference - Stackbar & Bar (188-195)
mv "docs-cli-stackbar-mode.md" "188-docs-cli-stackbar-mode.md"
mv "docs-cli-bar-configuration.md" "189-docs-cli-bar-configuration.md"

# CLI Reference - Autostart & Misc (196-203)
mv "docs-cli-enable-autostart.md" "196-docs-cli-enable-autostart.md"
mv "docs-cli-disable-autostart.md" "197-docs-cli-disable-autostart.md"

# CLI Reference - Data & System (198-203)
mv "docs-cli-data-directory.md" "198-docs-cli-data-directory.md"
mv "docs-cli-log.md" "199-docs-cli-log.md"
mv "docs-cli-whkdrc.md" "200-docs-cli-whkdrc.md"
mv "docs-cli-gui.md" "201-docs-cli-gui.md"
mv "docs-cli-query.md" "202-docs-cli-query.md"
mv "docs-cli-visible-windows.md" "203-docs-cli-visible-windows.md"
mv "docs-cli-global-state.md" "204-docs-cli-global-state.md"
mv "docs-cli-check.md" "205-docs-cli-check.md"
mv "docs-cli-kill.md" "206-docs-cli-kill.md"
mv "docs-cli-license.md" "207-docs-cli-license.md"

echo "Rename complete!"
