const fs = require('fs');

// Read metadata.json
const metadata = JSON.parse(fs.readFileSync('metadata.json', 'utf8'));

// Create mapping from old to new filenames
const oldToNew = {
  "docs-index.md": "001-docs-index.md",
  "docs-installation.md": "002-docs-installation.md",
  "docs-usage-stacking-windows.md": "003-docs-usage-stacking-windows.md",
  "docs-usage-moving-windows.md": "004-docs-usage-moving-windows.md",
  "docs-usage-moving-windows-across-workspaces.md": "005-docs-usage-moving-windows-across-workspaces.md",
  "docs-usage-focusing-windows.md": "006-docs-usage-focusing-windows.md",
  "docs-usage-focusing-workspaces.md": "007-docs-usage-focusing-workspaces.md",
  "docs-design.md": "008-docs-design.md",
  "docs-example-configurations.md": "009-docs-example-configurations.md",
  "docs-common-workflows-autohotkey.md": "010-docs-common-workflows-autohotkey.md",
  "docs-common-workflows-animations.md": "011-docs-common-workflows-animations.md",
  "docs-common-workflows-autostart.md": "012-docs-common-workflows-autostart.md",
  "docs-common-workflows-borders.md": "013-docs-common-workflows-borders.md",
  "docs-common-workflows-dynamic-layout-switching.md": "014-docs-common-workflows-dynamic-layout-switching.md",
  "docs-common-workflows-floating-applications.md": "015-docs-common-workflows-floating-applications.md",
  "docs-common-workflows-force-manage-windows.md": "016-docs-common-workflows-force-manage-windows.md",
  "docs-common-workflows-ignore-windows.md": "017-docs-common-workflows-ignore-windows.md",
  "docs-common-workflows-komorebi-config-home.md": "018-docs-common-workflows-komorebi-config-home.md",
  "docs-common-workflows-layout-ratios.md": "019-docs-common-workflows-layout-ratios.md",
  "docs-common-workflows-mouse-follows-focus.md": "020-docs-common-workflows-mouse-follows-focus.md",
  "docs-common-workflows-multi-monitor-setup.md": "021-docs-common-workflows-multi-monitor-setup.md",
  "docs-common-workflows-multiple-bar-instances.md": "022-docs-common-workflows-multiple-bar-instances.md",
  "docs-common-workflows-remove-gaps.md": "023-docs-common-workflows-remove-gaps.md",
  "docs-common-workflows-stackbar.md": "024-docs-common-workflows-stackbar.md",
  "docs-common-workflows-tray-and-multi-window-applications.md": "025-docs-common-workflows-tray-and-multi-window-applications.md",
  "docs-troubleshooting.md": "026-docs-troubleshooting.md",
  "docs-cli-start.md": "027-docs-cli-start.md",
  "docs-cli-stop.md": "028-docs-cli-stop.md",
  "docs-cli-state.md": "029-docs-cli-state.md",
  "docs-cli-reload-configuration.md": "030-docs-cli-reload-configuration.md",
  "docs-cli-watch-configuration.md": "031-docs-cli-watch-configuration.md",
  "docs-cli-replace-configuration.md": "032-docs-cli-replace-configuration.md",
  "docs-cli-configuration.md": "033-docs-cli-configuration.md",
  "docs-cli-quick-save-resize.md": "034-docs-cli-quick-save-resize.md",
  "docs-cli-quick-load-resize.md": "035-docs-cli-quick-load-resize.md",
  "docs-cli-save-resize.md": "036-docs-cli-save-resize.md",
  "docs-cli-load-resize.md": "037-docs-cli-load-resize.md",
  "docs-cli-focus.md": "038-docs-cli-focus.md",
  "docs-cli-focus-monitor.md": "039-docs-cli-focus-monitor.md",
  "docs-cli-focus-monitor-at-cursor.md": "040-docs-cli-focus-monitor-at-cursor.md",
  "docs-cli-focus-monitor-workspace.md": "041-docs-cli-focus-monitor-workspace.md",
  "docs-cli-focus-workspace.md": "042-docs-cli-focus-workspace.md",
  "docs-cli-focus-named-workspace.md": "043-docs-cli-focus-named-workspace.md",
  "docs-cli-focus-last-workspace.md": "044-docs-cli-focus-last-workspace.md",
  "docs-cli-focus-workspaces.md": "045-docs-cli-focus-workspaces.md",
  "docs-cli-focus-stack-window.md": "046-docs-cli-focus-stack-window.md",
  "docs-cli-eager-focus.md": "047-docs-cli-eager-focus.md",
  "docs-cli-force-focus.md": "048-docs-cli-force-focus.md",
  "docs-cli-cycle-focus.md": "049-docs-cli-cycle-focus.md",
  "docs-cli-move.md": "050-docs-cli-move.md",
  "docs-cli-move-to-workspace.md": "051-docs-cli-move-to-workspace.md",
  "docs-cli-move-to-named-workspace.md": "052-docs-cli-move-to-named-workspace.md",
  "docs-cli-move-to-monitor.md": "053-docs-cli-move-to-monitor.md",
  "docs-cli-move-to-monitor-workspace.md": "054-docs-cli-move-to-monitor-workspace.md",
  "docs-cli-move-to-last-workspace.md": "055-docs-cli-move-to-last-workspace.md",
  "docs-cli-move-workspace-to-monitor.md": "056-docs-cli-move-workspace-to-monitor.md",
  "docs-cli-cycle-move.md": "057-docs-cli-cycle-move.md",
  "docs-cli-cycle-move-to-workspace.md": "058-docs-cli-cycle-move-to-workspace.md",
  "docs-cli-cycle-move-to-monitor.md": "059-docs-cli-cycle-move-to-monitor.md",
  "docs-cli-cycle-move-workspace-to-monitor.md": "060-docs-cli-cycle-move-workspace-to-monitor.md",
  "docs-cli-send-to-workspace.md": "061-docs-cli-send-to-workspace.md",
  "docs-cli-send-to-named-workspace.md": "062-docs-cli-send-to-named-workspace.md",
  "docs-cli-send-to-monitor.md": "063-docs-cli-send-to-monitor.md",
  "docs-cli-send-to-monitor-workspace.md": "064-docs-cli-send-to-monitor-workspace.md",
  "docs-cli-send-to-last-workspace.md": "065-docs-cli-send-to-last-workspace.md",
  "docs-cli-new-workspace.md": "066-docs-cli-new-workspace.md",
  "docs-cli-close-workspace.md": "067-docs-cli-close-workspace.md",
  "docs-cli-workspace-name.md": "068-docs-cli-workspace-name.md",
  "docs-cli-cycle-workspace.md": "069-docs-cli-cycle-workspace.md",
  "docs-cli-cycle-empty-workspace.md": "070-docs-cli-cycle-empty-workspace.md",
  "docs-cli-swap-workspaces-with-monitor.md": "071-docs-cli-swap-workspaces-with-monitor.md",
  "docs-cli-workspace-padding.md": "072-docs-cli-workspace-padding.md",
  "docs-cli-adjust-workspace-padding.md": "073-docs-cli-adjust-workspace-padding.md",
  "docs-cli-focused-workspace-padding.md": "074-docs-cli-focused-workspace-padding.md",
  "docs-cli-workspace-layout.md": "075-docs-cli-workspace-layout.md",
  "docs-cli-change-layout.md": "076-docs-cli-change-layout.md",
  "docs-cli-cycle-layout.md": "077-docs-cli-cycle-layout.md",
  "docs-cli-flip-layout.md": "078-docs-cli-flip-layout.md",
  "docs-cli-workspace-tiling.md": "079-docs-cli-workspace-tiling.md",
  "docs-cli-named-workspace-tiling.md": "080-docs-cli-named-workspace-tiling.md",
  "docs-cli-workspace-layout-rule.md": "081-docs-cli-workspace-layout-rule.md",
  "docs-cli-named-workspace-layout-rule.md": "082-docs-cli-named-workspace-layout-rule.md",
  "docs-cli-named-workspace-layout.md": "083-docs-cli-named-workspace-layout.md",
  "docs-cli-ensure-workspaces.md": "084-docs-cli-ensure-workspaces.md",
  "docs-cli-ensure-named-workspaces.md": "085-docs-cli-ensure-named-workspaces.md",
  "docs-cli-container-padding.md": "086-docs-cli-container-padding.md",
  "docs-cli-adjust-container-padding.md": "087-docs-cli-adjust-container-padding.md",
  "docs-cli-focused-workspace-container-padding.md": "088-docs-cli-focused-workspace-container-padding.md",
  "docs-cli-named-workspace-container-padding.md": "089-docs-cli-named-workspace-container-padding.md",
  "docs-cli-stack.md": "090-docs-cli-stack.md",
  "docs-cli-unstack.md": "091-docs-cli-unstack.md",
  "docs-cli-stack-all.md": "092-docs-cli-stack-all.md",
  "docs-cli-unstack-all.md": "093-docs-cli-unstack-all.md",
  "docs-cli-cycle-stack.md": "094-docs-cli-cycle-stack.md",
  "docs-cli-cycle-stack-index.md": "095-docs-cli-cycle-stack-index.md",
  "docs-cli-promote.md": "096-docs-cli-promote.md",
  "docs-cli-promote-window.md": "097-docs-cli-promote-window.md",
  "docs-cli-promote-focus.md": "098-docs-cli-promote-focus.md",
  "docs-cli-promote-swap.md": "099-docs-cli-promote-swap.md",
  "docs-cli-cancel-preselect.md": "100-docs-cli-cancel-preselect.md",
  "docs-cli-preselect-direction.md": "101-docs-cli-preselect-direction.md",
  "docs-cli-scrolling-layout-columns.md": "102-docs-cli-scrolling-layout-columns.md",
  "docs-cli-close.md": "103-docs-cli-close.md",
  "docs-cli-minimize.md": "104-docs-cli-minimize.md",
  "docs-cli-restore-windows.md": "105-docs-cli-restore-windows.md",
  "docs-cli-retile.md": "106-docs-cli-retile.md",
  "docs-cli-toggle-monocle.md": "107-docs-cli-toggle-monocle.md",
  "docs-cli-toggle-maximize.md": "108-docs-cli-toggle-maximize.md",
  "docs-cli-resize-axis.md": "109-docs-cli-resize-axis.md",
  "docs-cli-resize-delta.md": "110-docs-cli-resize-delta.md",
  "docs-cli-resize-edge.md": "111-docs-cli-resize-edge.md",
  "docs-cli-toggle-float.md": "112-docs-cli-toggle-float.md",
  "docs-cli-toggle-float-override.md": "113-docs-cli-toggle-float-override.md",
  "docs-cli-toggle-workspace-float-override.md": "114-docs-cli-toggle-workspace-float-override.md",
  "docs-cli-cycle-monitor.md": "115-docs-cli-cycle-monitor.md",
  "docs-cli-monitor-information.md": "116-docs-cli-monitor-information.md",
  "docs-cli-monitor-work-area-offset.md": "117-docs-cli-monitor-work-area-offset.md",
  "docs-cli-display-index-preference.md": "118-docs-cli-display-index-preference.md",
  "docs-cli-monitor-index-preference.md": "119-docs-cli-monitor-index-preference.md",
  "docs-cli-toggle-tiling.md": "120-docs-cli-toggle-tiling.md",
  "docs-cli-toggle-pause.md": "121-docs-cli-toggle-pause.md",
  "docs-cli-toggle-lock.md": "122-docs-cli-toggle-lock.md",
  "docs-cli-toggle-shortcuts.md": "123-docs-cli-toggle-shortcuts.md",
  "docs-cli-toggle-title-bars.md": "124-docs-cli-toggle-title-bars.md",
  "docs-cli-toggle-transparency.md": "125-docs-cli-toggle-transparency.md",
  "docs-cli-toggle-mouse-follows-focus.md": "126-docs-cli-toggle-mouse-follows-focus.md",
  "docs-cli-mouse-follows-focus.md": "127-docs-cli-mouse-follows-focus.md",
  "docs-cli-toggle-workspace-layer.md": "128-docs-cli-toggle-workspace-layer.md",
  "docs-cli-toggle-cross-monitor-move-behaviour.md": "129-docs-cli-toggle-cross-monitor-move-behaviour.md",
  "docs-cli-cross-monitor-move-behaviour.md": "130-docs-cli-cross-monitor-move-behaviour.md",
  "docs-cli-toggle-window-based-work-area-offset.md": "131-docs-cli-toggle-window-based-work-area-offset.md",
  "docs-cli-global-work-area-offset.md": "132-docs-cli-global-work-area-offset.md",
  "docs-cli-workspace-work-area-offset.md": "133-docs-cli-workspace-work-area-offset.md",
  "docs-cli-toggle-window-container-behaviour.md": "134-docs-cli-toggle-window-container-behaviour.md",
  "docs-cli-toggle-workspace-window-container-behaviour.md": "135-docs-cli-toggle-workspace-window-container-behaviour.md",
  "docs-cli-unmanaged-window-operation-behaviour.md": "136-docs-cli-unmanaged-window-operation-behaviour.md",
  "docs-cli-manage.md": "137-docs-cli-manage.md",
  "docs-cli-unmanage.md": "138-docs-cli-unmanage.md",
  "docs-cli-manage-rule.md": "139-docs-cli-manage-rule.md",
  "docs-cli-ignore-rule.md": "140-docs-cli-ignore-rule.md",
  "docs-cli-workspace-rule.md": "141-docs-cli-workspace-rule.md",
  "docs-cli-named-workspace-rule.md": "142-docs-cli-named-workspace-rule.md",
  "docs-cli-initial-workspace-rule.md": "143-docs-cli-initial-workspace-rule.md",
  "docs-cli-initial-named-workspace-rule.md": "144-docs-cli-initial-named-workspace-rule.md",
  "docs-cli-session-float-rules.md": "145-docs-cli-session-float-rules.md",
  "docs-cli-session-float-rule.md": "146-docs-cli-session-float-rule.md",
  "docs-cli-clear-workspace-rules.md": "147-docs-cli-clear-workspace-rules.md",
  "docs-cli-clear-named-workspace-rules.md": "148-docs-cli-clear-named-workspace-rules.md",
  "docs-cli-clear-all-workspace-rules.md": "149-docs-cli-clear-all-workspace-rules.md",
  "docs-cli-clear-session-float-rules.md": "150-docs-cli-clear-session-float-rules.md",
  "docs-cli-clear-workspace-layout-rules.md": "151-docs-cli-clear-workspace-layout-rules.md",
  "docs-cli-clear-named-workspace-layout-rules.md": "152-docs-cli-clear-named-workspace-layout-rules.md",
  "docs-cli-enforce-workspace-rules.md": "153-docs-cli-enforce-workspace-rules.md",
  "docs-cli-animation.md": "154-docs-cli-animation.md",
  "docs-cli-animation-duration.md": "155-docs-cli-animation-duration.md",
  "docs-cli-animation-fps.md": "156-docs-cli-animation-fps.md",
  "docs-cli-animation-style.md": "157-docs-cli-animation-style.md",
  "docs-cli-transparency.md": "158-docs-cli-transparency.md",
  "docs-cli-transparency-alpha.md": "159-docs-cli-transparency-alpha.md",
  "docs-cli-border.md": "160-docs-cli-border.md",
  "docs-cli-border-width.md": "161-docs-cli-border-width.md",
  "docs-cli-border-colour.md": "162-docs-cli-border-colour.md",
  "docs-cli-border-style.md": "163-docs-cli-border-style.md",
  "docs-cli-border-offset.md": "164-docs-cli-border-offset.md",
  "docs-cli-border-implementation.md": "165-docs-cli-border-implementation.md",
  "docs-cli-invisible-borders.md": "166-docs-cli-invisible-borders.md",
  "docs-cli-remove-title-bar.md": "167-docs-cli-remove-title-bar.md",
  "docs-cli-identify-layered-application.md": "168-docs-cli-identify-layered-application.md",
  "docs-cli-identify-tray-application.md": "169-docs-cli-identify-tray-application.md",
  "docs-cli-identify-object-name-change-application.md": "170-docs-cli-identify-object-name-change-application.md",
  "docs-cli-window-hiding-behaviour.md": "171-docs-cli-window-hiding-behaviour.md",
  "docs-cli-complete-configuration.md": "172-docs-cli-complete-configuration.md",
  "docs-cli-generate-static-config.md": "173-docs-cli-generate-static-config.md",
  "docs-cli-static-config-schema.md": "174-docs-cli-static-config-schema.md",
  "docs-cli-application-specific-configuration-schema.md": "175-docs-cli-application-specific-configuration-schema.md",
  "docs-cli-convert-app-specific-configuration.md": "176-docs-cli-convert-app-specific-configuration.md",
  "docs-cli-fetch-app-specific-configuration.md": "177-docs-cli-fetch-app-specific-configuration.md",
  "docs-cli-ahk-app-specific-configuration.md": "178-docs-cli-ahk-app-specific-configuration.md",
  "docs-cli-pwsh-app-specific-configuration.md": "179-docs-cli-pwsh-app-specific-configuration.md",
  "docs-cli-subscribe-socket.md": "180-docs-cli-subscribe-socket.md",
  "docs-cli-unsubscribe-socket.md": "181-docs-cli-unsubscribe-socket.md",
  "docs-cli-subscribe-pipe.md": "182-docs-cli-subscribe-pipe.md",
  "docs-cli-unsubscribe-pipe.md": "183-docs-cli-unsubscribe-pipe.md",
  "docs-cli-socket-schema.md": "184-docs-cli-socket-schema.md",
  "docs-cli-notification-schema.md": "185-docs-cli-notification-schema.md",
  "docs-cli-stackbar-mode.md": "186-docs-cli-stackbar-mode.md",
  "docs-cli-bar-configuration.md": "187-docs-cli-bar-configuration.md",
  "docs-cli-enable-autostart.md": "188-docs-cli-enable-autostart.md",
  "docs-cli-disable-autostart.md": "189-docs-cli-disable-autostart.md",
  "docs-cli-data-directory.md": "190-docs-cli-data-directory.md",
  "docs-cli-log.md": "191-docs-cli-log.md",
  "docs-cli-whkdrc.md": "192-docs-cli-whkdrc.md",
  "docs-cli-gui.md": "193-docs-cli-gui.md",
  "docs-cli-query.md": "194-docs-cli-query.md",
  "docs-cli-visible-windows.md": "195-docs-cli-visible-windows.md",
  "docs-cli-global-state.md": "196-docs-cli-global-state.md",
  "docs-cli-check.md": "197-docs-cli-check.md",
  "docs-cli-kill.md": "198-docs-cli-kill.md",
  "docs-cli-license.md": "199-docs-cli-license.md",
  "docs-cli-quickstart.md": "200-docs-cli-quickstart.md"
};

// Update documents
metadata.documents.forEach(doc => {
  const oldPath = doc.file_path;
  if (oldToNew[oldPath]) {
    doc.original_file_path = oldPath;
    doc.file_path = oldToNew[oldPath];
  }
});

// Add organization metadata
metadata.organization = {
  method: "sequential-numbering",
  organized_at: new Date().toISOString(),
  total_files: metadata.documents.length,
  categories: [
    "Introduction & Overview",
    "Usage Guides",
    "Configuration & Design",
    "Common Workflows",
    "Troubleshooting",
    "CLI Reference"
  ]
};

// Write updated metadata
fs.writeFileSync('metadata.json', JSON.stringify(metadata, null, 2));
console.log('Metadata updated successfully!');
